### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by Kariaki58** [Kariaki58/MusicIO#17]
I'm facing issues, with the home.html to get data from base.html
it's going to be like that for now, till i figure out the issue

**Comment by cholthi** [comment]
When you say "am facing issues getting data from base.html", what exactly do you mean?. What were you trying to do and what error did you get?

**Comment by Kariaki58** [comment]
The issues has been fixed.
I modified your message flashing, added a category, to avoid message listing
